"""
This type stub file was generated by pyright.
"""

"""Perform aggregation operations on a collection or database."""
class _AggregationCommand(object):
    """The internal abstract base class for aggregation cursors.

    Should not be called directly by application developers. Use
    :meth:`pymongo.collection.Collection.aggregate`, or
    :meth:`pymongo.database.Database.aggregate` instead.
    """
    def __init__(self, target, cursor_class, pipeline, options, explicit_session, user_fields=..., result_processor=...) -> None:
        ...
    
    def get_read_preference(self, session):
        ...
    
    def get_cursor(self, session, server, sock_info, slave_ok):
        ...
    


class _CollectionAggregationCommand(_AggregationCommand):
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class _CollectionRawAggregationCommand(_CollectionAggregationCommand):
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class _DatabaseAggregationCommand(_AggregationCommand):
    ...


