"""
This type stub file was generated by pyright.
"""

"""MONGODB-AWS Authentication helpers."""
class _AwsSaslContext(AwsSaslContext):
    def binary_type(self):
        """Return the bson.binary.Binary type."""
        ...
    
    def bson_encode(self, doc):
        """Encode a dictionary to BSON."""
        ...
    
    def bson_decode(self, data):
        """Decode BSON to a dictionary."""
        ...
    


