"""
This type stub file was generated by pyright.
"""

import functools
from collections import namedtuple
from bson.py3compat import PY3
from pymongo.auth_aws import _authenticate_aws

"""Authentication helpers."""
HAVE_KERBEROS = True
_USE_PRINCIPAL = False
MECHANISMS = frozenset(['GSSAPI', 'MONGODB-CR', 'MONGODB-X509', 'MONGODB-AWS', 'PLAIN', 'SCRAM-SHA-1', 'SCRAM-SHA-256', 'DEFAULT'])
class _Cache(object):
    __slots__ = ...
    _hash_val = ...
    def __init__(self) -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    


MongoCredential = namedtuple('MongoCredential', ['mechanism', 'source', 'username', 'password', 'mechanism_properties', 'cache'])
GSSAPIProperties = namedtuple('GSSAPIProperties', ['service_name', 'canonicalize_host_name', 'service_realm'])
_AWSProperties = namedtuple('AWSProperties', ['aws_session_token'])
if PY3:
    _from_bytes = int.from_bytes
    _to_bytes = int.to_bytes
else:
    ...
_AUTH_MAP = { 'CRAM-MD5': _authenticate_cram_md5,'GSSAPI': _authenticate_gssapi,'MONGODB-CR': _authenticate_mongo_cr,'MONGODB-X509': _authenticate_x509,'MONGODB-AWS': _authenticate_aws,'PLAIN': _authenticate_plain,'SCRAM-SHA-1': functools.partial(_authenticate_scram, mechanism='SCRAM-SHA-1'),'SCRAM-SHA-256': functools.partial(_authenticate_scram, mechanism='SCRAM-SHA-256'),'DEFAULT': _authenticate_default }
class _AuthContext(object):
    def __init__(self, credentials) -> None:
        ...
    
    @staticmethod
    def from_credentials(creds):
        ...
    
    def speculate_command(self):
        ...
    
    def parse_response(self, ismaster):
        ...
    
    def speculate_succeeded(self):
        ...
    


class _ScramContext(_AuthContext):
    def __init__(self, credentials, mechanism) -> None:
        ...
    
    def speculate_command(self):
        ...
    


class _X509Context(_AuthContext):
    def speculate_command(self):
        ...
    


_SPECULATIVE_AUTH_MAP = { 'MONGODB-X509': _X509Context,'SCRAM-SHA-1': functools.partial(_ScramContext, mechanism='SCRAM-SHA-1'),'SCRAM-SHA-256': functools.partial(_ScramContext, mechanism='SCRAM-SHA-256'),'DEFAULT': functools.partial(_ScramContext, mechanism='SCRAM-SHA-256') }
def authenticate(credentials, sock_info):
    """Authenticate sock_info."""
    ...

def logout(source, sock_info):
    """Log out from a database."""
    ...

