"""
This type stub file was generated by pyright.
"""

_SUPPORTED_COMPRESSORS = set(["snappy", "zlib", "zstd"])
_NO_COMPRESSION = set(['ismaster'])
def validate_compressors(dummy, value):
    ...

def validate_zlib_compression_level(option, value):
    ...

class CompressionSettings(object):
    def __init__(self, compressors, zlib_compression_level) -> None:
        ...
    
    def get_compression_context(self, compressors):
        ...
    


class SnappyContext(object):
    compressor_id = ...
    @staticmethod
    def compress(data):
        ...
    


class ZlibContext(object):
    compressor_id = ...
    def __init__(self, level) -> None:
        ...
    


class ZstdContext(object):
    compressor_id = ...
    @staticmethod
    def compress(data):
        ...
    


def decompress(data, compressor_id):
    ...

