"""
This type stub file was generated by pyright.
"""

import os
import subprocess
import sys

"""Support for spawning a daemon process.

PyMongo only attempts to spawn the mongocryptd daemon process when automatic
client-side field level encryption is enabled. See
:ref:`automatic-client-side-encryption` for more info.
"""
_WAIT_TIMEOUT = 10
_THIS_FILE = os.path.realpath(__file__)
if sys.version_info[0] < 3:
    ...
else:
    ...
if sys.platform == 'win32':
    _DETACHED_PROCESS = getattr(subprocess, 'DETACHED_PROCESS', 8)
else:
    ...
