"""
This type stub file was generated by pyright.
"""

from collections import namedtuple

"""Advanced options for MongoDB drivers implemented on top of PyMongo."""
class DriverInfo(namedtuple('DriverInfo', ['name', 'version', 'platform'])):
    """Info about a driver wrapping PyMongo.

    The MongoDB server logs PyMongo's name, version, and platform whenever
    PyMongo establishes a connection. A driver implemented on top of PyMongo
    can add its own info to this log message. Initialize with three strings
    like 'MyDriver', '1.2.3', 'some platform info'. Any of these strings may be
    None to accept PyMongo's default.
    """
    def __new__(cls, name=..., version=..., platform=...):
        ...
    


