"""
This type stub file was generated by pyright.
"""

"""Bits and pieces used by the driver that don't really fit elsewhere."""
_SHUTDOWN_CODES = frozenset([11600, 91])
_NOT_MASTER_CODES = frozenset([10107, 13435, 11602, 13436, 189]) | _SHUTDOWN_CODES
_RETRYABLE_ERROR_CODES = _NOT_MASTER_CODES | frozenset([7, 6, 89, 9001, 262])
_UUNDER = u"_"
