"""
This type stub file was generated by pyright.
"""

"""Parse a response to the 'ismaster' command."""
class IsMaster(object):
    __slots__ = ...
    def __init__(self, doc, awaitable=...) -> None:
        """Parse an ismaster response from the server."""
        ...
    
    @property
    def document(self):
        """The complete ismaster command response document.

        .. versionadded:: 3.4
        """
        ...
    
    @property
    def server_type(self):
        ...
    
    @property
    def all_hosts(self):
        """List of hosts, passives, and arbiters known to this server."""
        ...
    
    @property
    def tags(self):
        """Replica set member tags or empty dict."""
        ...
    
    @property
    def primary(self):
        """This server's opinion about who the primary is, or None."""
        ...
    
    @property
    def replica_set_name(self):
        """Replica set name or None."""
        ...
    
    @property
    def max_bson_size(self):
        ...
    
    @property
    def max_message_size(self):
        ...
    
    @property
    def max_write_batch_size(self):
        ...
    
    @property
    def min_wire_version(self):
        ...
    
    @property
    def max_wire_version(self):
        ...
    
    @property
    def set_version(self):
        ...
    
    @property
    def election_id(self):
        ...
    
    @property
    def cluster_time(self):
        ...
    
    @property
    def logical_session_timeout_minutes(self):
        ...
    
    @property
    def is_writable(self):
        ...
    
    @property
    def is_readable(self):
        ...
    
    @property
    def me(self):
        ...
    
    @property
    def last_write_date(self):
        ...
    
    @property
    def compressors(self):
        ...
    
    @property
    def sasl_supported_mechs(self):
        """Supported authentication mechanisms for the current user.

        For example::

            >>> ismaster.sasl_supported_mechs
            ["SCRAM-SHA-1", "SCRAM-SHA-256"]

        """
        ...
    
    @property
    def speculative_authenticate(self):
        """The speculativeAuthenticate field."""
        ...
    
    @property
    def topology_version(self):
        ...
    
    @property
    def awaitable(self):
        ...
    


