"""
This type stub file was generated by pyright.
"""

"""Criteria to select ServerDescriptions based on maxStalenessSeconds.

The Max Staleness Spec says: When there is a known primary P,
a secondary S's staleness is estimated with this formula:

  (S.lastUpdateTime - S.lastWriteDate) - (P.lastUpdateTime - P.lastWriteDate)
  + heartbeatFrequencyMS

When there is no known primary, a secondary S's staleness is estimated with:

  SMax.lastWriteDate - S.lastWriteDate + heartbeatFrequencyMS

where "SMax" is the secondary with the greatest lastWriteDate.
"""
IDLE_WRITE_PERIOD = 10
SMALLEST_MAX_STALENESS = 90
def select(max_staleness, selection):
    """Apply max_staleness, in seconds, to a Selection."""
    ...

