"""
This type stub file was generated by pyright.
"""

import logging as _logging
import re as _re

"""Support for requesting and verifying OCSP responses."""
_LOGGER = _logging.getLogger(__name__)
_CERT_REGEX = _re.compile(b'-----BEGIN CERTIFICATE[^\r\n]+.+?-----END CERTIFICATE[^\r\n]+', _re.DOTALL)
