"""
This type stub file was generated by pyright.
"""

"""Utilities for caching OCSP responses."""
class _OCSPCache(object):
    """A cache for OCSP responses."""
    CACHE_KEY_TYPE = ...
    def __init__(self) -> None:
        ...
    
    def __setitem__(self, key, value):
        """Add/update a cache entry.

        'key' is of type cryptography.x509.ocsp.OCSPRequest
        'value' is of type cryptography.x509.ocsp.OCSPResponse

        Validity of the OCSP response must be checked by caller.
        """
        ...
    
    def __getitem__(self, item):
        """Get a cache entry if it exists.

        'item' is of type cryptography.x509.ocsp.OCSPRequest

        Raises KeyError if the item is not in the cache.
        """
        ...
    


