"""
This type stub file was generated by pyright.
"""

"""Represent a response from the server."""
class Response(object):
    __slots__ = ...
    def __init__(self, data, address, request_id, duration, from_command, docs) -> None:
        """Represent a response from the server.

        :Parameters:
          - `data`: A network response message.
          - `address`: (host, port) of the source server.
          - `request_id`: The request id of this operation.
          - `duration`: The duration of the operation.
          - `from_command`: if the response is the result of a db command.
        """
        ...
    
    @property
    def data(self):
        """Server response's raw BSON bytes."""
        ...
    
    @property
    def address(self):
        """(host, port) of the source server."""
        ...
    
    @property
    def request_id(self):
        """The request id of this operation."""
        ...
    
    @property
    def duration(self):
        """The duration of the operation."""
        ...
    
    @property
    def from_command(self):
        """If the response is a result from a db command."""
        ...
    
    @property
    def docs(self):
        """The decoded document(s)."""
        ...
    


class ExhaustResponse(Response):
    __slots__ = ...
    def __init__(self, data, address, socket_info, pool, request_id, duration, from_command, docs) -> None:
        """Represent a response to an exhaust cursor's initial query.

        :Parameters:
          - `data`:  A network response message.
          - `address`: (host, port) of the source server.
          - `socket_info`: The SocketInfo used for the initial query.
          - `pool`: The Pool from which the SocketInfo came.
          - `request_id`: The request id of this operation.
          - `duration`: The duration of the operation.
          - `from_command`: If the response is the result of a db command.
        """
        ...
    
    @property
    def socket_info(self):
        """The SocketInfo used for the initial query.

        The server will send batches on this socket, without waiting for
        getMores from the client, until the result set is exhausted or there
        is an error.
        """
        ...
    
    @property
    def pool(self):
        """The Pool from which the SocketInfo came."""
        ...
    


