"""
This type stub file was generated by pyright.
"""

"""Represent one server the driver is connected to."""
class ServerDescription(object):
    """Immutable representation of one server.

    :Parameters:
      - `address`: A (host, port) pair
      - `ismaster`: Optional IsMaster instance
      - `round_trip_time`: Optional float
      - `error`: Optional, the last error attempting to connect to the server
    """
    __slots__ = ...
    def __init__(self, address, ismaster=..., round_trip_time=..., error=...) -> None:
        ...
    
    @property
    def address(self):
        """The address (host, port) of this server."""
        ...
    
    @property
    def server_type(self):
        """The type of this server."""
        ...
    
    @property
    def server_type_name(self):
        """The server type as a human readable string.

        .. versionadded:: 3.4
        """
        ...
    
    @property
    def all_hosts(self):
        """List of hosts, passives, and arbiters known to this server."""
        ...
    
    @property
    def tags(self):
        ...
    
    @property
    def replica_set_name(self):
        """Replica set name or None."""
        ...
    
    @property
    def primary(self):
        """This server's opinion about who the primary is, or None."""
        ...
    
    @property
    def max_bson_size(self):
        ...
    
    @property
    def max_message_size(self):
        ...
    
    @property
    def max_write_batch_size(self):
        ...
    
    @property
    def min_wire_version(self):
        ...
    
    @property
    def max_wire_version(self):
        ...
    
    @property
    def set_version(self):
        ...
    
    @property
    def election_id(self):
        ...
    
    @property
    def cluster_time(self):
        ...
    
    @property
    def election_tuple(self):
        ...
    
    @property
    def me(self):
        ...
    
    @property
    def logical_session_timeout_minutes(self):
        ...
    
    @property
    def last_write_date(self):
        ...
    
    @property
    def last_update_time(self):
        ...
    
    @property
    def round_trip_time(self):
        """The current average latency or None."""
        ...
    
    @property
    def error(self):
        """The last error attempting to connect to the server, or None."""
        ...
    
    @property
    def is_writable(self):
        ...
    
    @property
    def is_readable(self):
        ...
    
    @property
    def mongos(self):
        ...
    
    @property
    def is_server_type_known(self):
        ...
    
    @property
    def retryable_writes_supported(self):
        """Checks if this server supports retryable writes."""
        ...
    
    @property
    def retryable_reads_supported(self):
        """Checks if this server supports retryable writes."""
        ...
    
    @property
    def topology_version(self):
        ...
    
    def to_unknown(self, error=...):
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    
    def __repr__(self):
        ...
    
    _host_to_round_trip_time = ...


