"""
This type stub file was generated by pyright.
"""

from bson.py3compat import PY3

"""Support for resolving hosts and options from mongodb+srv:// URIs."""
if PY3:
    def maybe_decode(text):
        ...
    
else:
    def maybe_decode(text):
        ...
    
class _SrvResolver(object):
    def __init__(self, fqdn, connect_timeout=...) -> None:
        ...
    
    def get_options(self):
        ...
    
    def get_hosts(self):
        ...
    
    def get_hosts_and_min_ttl(self):
        ...
    


