"""
This type stub file was generated by pyright.
"""

import sys

if sys.version_info[0] < 3:
    ...
else:
    _unicode = lambda value: value
def match_hostname(cert, hostname):
    """Verify that *cert* (in decoded format as returned by
    SSLSocket.getpeercert()) matches the *hostname*.  RFC 2818 and RFC 6125
    rules are followed.

    CertificateError is raised on failure. On success, the function
    returns nothing.
    """
    ...

