"""
This type stub file was generated by pyright.
"""

from aiohttp import ClientWebSocketResponse
from aiohttp.client_reqrep import ClientResponse
from ..NetClient import BaseClient
from ..Cert import Cert

class WebsocketClient(BaseClient):
    """
    implements BaseClient with websocket protocol
    """
    def __init__(self, cert: Cert, compress: bool = ...) -> None:
        ...
    
    async def send(self, url: str, data) -> ClientResponse:
        ...
    
    def on_recv_append(self, callback):
        ...
    
    async def heartbeater(self, ws_conn: ClientWebSocketResponse):
        ...
    
    def run(self):
        ...
    


