"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from .types import BaseSession, CommandType
from khl.Message import Msg
from typing import Any, Sequence, overload
from khl.Bot import Bot

class BaseCommand(ABC):
    trigger: str
    help: str
    __bot: Bot
    _type: CommandType
    use_help: bool = ...
    with_reply: bool = ...
    with_mention: bool = ...
    def __init__(self) -> None:
        ...
    
    @overload
    @abstractmethod
    async def execute(self, command_str: str, args: Sequence[str], msg: Msg) -> Any:
        """
        docstring
        """
        ...
    
    @abstractmethod
    async def execute(self, session: BaseSession) -> Any:
        """
        docstring
        """
        ...
    
    @abstractmethod
    async def run_func(self, session: BaseSession) -> Any:
        """
        docstring
        """
        ...
    
    @abstractmethod
    async def func(self, session: BaseSession) -> Any:
        """
        docstring
        """
        ...
    
    @property
    def bot(self):
        ...
    
    def set_bot(self, bot):
        ...
    
    @property
    def type(self):
        ...
    


