"""
This type stub file was generated by pyright.
"""

from aiohttp import ClientResponse
from ..NetClient import BaseClient
from ..Cert import Cert

class WebhookClient(BaseClient):
    """
    implements BaseClient with webhook protocol
    """
    def __init__(self, *, port=..., route=..., compress: bool = ..., cert: Cert) -> None:
        """
        :param port: port to set webhook server on
        :param route: route for your webhook server
        :param compress: enable data compress or not, enabled as default
        :param cert: used to auth and data decrypt/encrypt
        """
        ...
    
    async def send(self, url: str, data) -> ClientResponse:
        ...
    
    def on_recv_append(self, callback):
        ...
    
    def run(self):
        ...
    


