"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Union
from .Cert import Cert
from .Message import TextMsg
from .Command import Command

class Bot:
    """
    Entity that interacts with user/environment
    """
    def __init__(self, *, cmd_prefix: Union[List[str], str, tuple] = ..., cert: Cert, compress: bool = ..., **kwargs) -> None:
        """
        Constructor of Bot

        :param cmd_prefix: accepted prefix for msg to be a command
        :param cert: used cert for connecting and decrypt
        :param compress: use compressed data to communicate
        """
        ...
    
    def add_command(self, cmd: Command):
        ...
    
    def command(self, name: str):
        ...
    
    async def send(self, channel_id: str, content: str, *, quote: str = ..., object_name: int = ..., nonce: str = ...) -> Any:
        ...
    
    def split_msg_args(self, msg: TextMsg):
        ...
    
    def gen_msg_handler(self):
        ...
    
    def run(self):
        ...
    


