"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Union
from khl import Cert
from khl.command_preview.typings import BaseCommand

class Bot:
    """
    Entity that interacts with user/environment
    """
    def __init__(self, *, cmd_prefix: Union[List[str], str, tuple] = ..., cert: Cert, compress: bool = ..., **kwargs) -> None:
        """
        Constructor of Bot

        :param cmd_prefix: accepted prefix for msg to be a command
        :param net_client: http connector/handler used, usually :class:`khl.webhook.WebhookClient`
        """
        ...
    
    def add_command(self, cmd: BaseCommand):
        ...
    
    def command(self, name: str):
        ...
    
    def gen_msg_handler_preview(self):
        ...
    
    async def send(self, channel_id: str, content: str, *, quote: str = ..., object_name: int = ..., nonce: str = ...) -> Any:
        ...
    
    def run(self):
        ...
    


