"""
This type stub file was generated by pyright.
"""

class Command:
    """
    Command class, used in Bot
    """
    def __init__(self, func, name: str) -> None:
        ...
    
    @staticmethod
    def command(name: str):
        """
        decorator to wrap a func into a Command

        :param name: the name of a Command, also used to trigger Command
        :return: wrapped Command
        """
        ...
    


