"""
This type stub file was generated by pyright.
"""

"""
hardcoded data, such as api request link
"""
API_BASE_URL = 'https://www.kaiheila.cn/api'
API_VERSION_NUMBER = 3
API_URL = <Expression>
