"""
This type stub file was generated by pyright.
"""

from abc import ABC
from enum import IntEnum

class Msg(ABC):
    class Types(IntEnum):
        TEXT = ...
        IMG = ...
        VIDEO = ...
        FILE = ...
        AUDIO = ...
        KMD = ...
        CARD = ...
    
    
    type: Types
    channel_type: str
    target_id: str
    author_id: str
    content: str
    msg_id: str
    msg_timestamp: int
    nonce: str
    extra: dict


class TextMsg(Msg):
    """
    represents a msg, recv from/send to server
    """
    def __init__(self, **kwargs) -> None:
        """
        all fields origin from server event object
        corresponding to official doc
        """
        ...
    


