"""
This type stub file was generated by pyright.
"""

from typing import Sequence, Union, overload
from .typings.base_command import BaseCommand
from .session import Session
from .typings.types import BaseSession
from .menu import MenuCommand
from khl.Message import Msg

class AppCommand(BaseCommand):
    intro: str
    parent: MenuCommand or None
    def __init__(self) -> None:
        ...
    
    @overload
    async def execute(self, command_str: str, args: Sequence[str], msg: Msg) -> BaseSession.ResultTypes or None:
        ...
    
    async def execute(self, session: Session) -> BaseSession.ResultTypes or None:
        ...
    
    async def run_func(self, session: BaseSession) -> BaseSession.ResultTypes or None:
        ...
    
    async def func(self, session: BaseSession) -> Union[BaseSession, BaseSession.ResultTypes, None]:
        ...
    


