"""
This type stub file was generated by pyright.
"""

from khl.Message import TextMsg
from typing import List, Mapping, Sequence, Tuple, Union
from .typings import BaseCommand

def parser(d: dict, prefixes: Union[List[str], str, tuple], commandMap: Mapping[str, BaseCommand]) -> Union[Tuple[str, Sequence[str], TextMsg], TextMsg]:
    ...

