"""
This type stub file was generated by pyright.
"""

from . import utils

r"""
模块：bangumi
功能：番剧相关
项目GitHub地址：https://github.com/Passkou/bilibili_api
项目主页：https://passkou.com/bilibili_api
   _____                _____    _____   _  __   ____    _    _
 |  __ \      /\      / ____|  / ____| | |/ /  / __ \  | |  | |
 | |__) |    /  \    | (___   | (___   | ' /  | |  | | | |  | |
 |  ___/    / /\ \    \___ \   \___ \  |  <   | |  | | | |  | |
 | |       / ____ \   ____) |  ____) | | . \  | |__| | | |__| |
 |_|      /_/    \_\ |_____/  |_____/  |_|\_\  \____/   \____/
"""
API = utils.get_api()
def get_meta(media_id: int, verify: utils.Verify = ...):
    """
    获取番剧元数据信息（评分，封面URL，标题等）
    :param media_id: media_id（URL中的/md*****）
    :param verify:
    :return:
    """
    ...

def get_short_comments_raw(media_id: int, ps: int = ..., sort: str = ..., cursor: str = ..., verify: utils.Verify = ...):
    """
    低层级API获取短评列表
    :param media_id:
    :param ps: 默认20即可
    :param sort: 排序方式default默认time按时间倒序
    :param cursor: 循环获取用，第一次调用本API返回中的next值
    :param verify:
    :return:
    """
    ...

def get_short_comments_g(media_id: int, order: str = ..., verify: utils.Verify = ...):
    """
    自动循环获取短评，使用生成器
    :param media_id:
    :param order: default（默认排序）time（时间倒序）
    :param verify:
    :return:
    """
    ...

def get_long_comments_raw(media_id: int, ps: int = ..., sort: str = ..., cursor: str = ..., verify: utils.Verify = ...):
    """
    低层级API获取长评列表
    :param media_id:
    :param ps: 默认20即可
    :param sort: 排序方式0默认1按时间倒序
    :param cursor: 循环获取用，第一次调用本API返回中的next值
    :param verify:
    :return:
    """
    ...

def get_long_comments_g(media_id: int, order: str = ..., verify: utils.Verify = ...):
    """
    自动循环获取长评，使用生成器
    :param media_id:
    :param order: default（默认排序）time（时间倒序）
    :param verify:
    :return:
    """
    ...

def get_episodes_list(season_id: int, verify: utils.Verify = ...):
    """
    获取季度分集列表
    :param season_id: season_id，从get_meta中获取
    :param verify:
    :return:
    """
    ...

def get_interact_data(season_id: int, verify: utils.Verify = ...):
    """
    获取番剧播放量，追番等信息
    :param season_id:
    :param verify:
    :return:
    """
    ...

def get_episode_info(epid: int, verify: utils.Verify = ...):
    """
    获取番剧ep信息
    :param epid:
    :param verify:
    :return:
    """
    ...

def get_collective_info(season_id: int, verify: utils.Verify = ...):
    """
    获取番剧全面概括信息,包括发布时间、剧集情况、stat等情况
    :param season_id:
    :param verify:
    :return:
    """
    ...

def set_follow(season_id: int, status: bool = ..., verify: utils.Verify = ...):
    """
    追番状态设置
    :param season_id:
    :param status: True追番False取消
    :param verify:
    :return:
    """
    ...

def set_follow_status(season_id: int, status: int = ..., verify: utils.Verify = ...):
    """
    追番状态设置
    :param season_id:
    :param status: 1想看2在看3已看
    :param verify:
    :return:
    """
    ...

def share_to_dynamic(epid: int, content: str, verify: utils.Verify = ...):
    """
    专栏转发
    :param epid: EP号
    :param content:
    :param verify:
    :return:
    """
    ...

