"""
This type stub file was generated by pyright.
"""

r"""
模块：异常库
功能：定义一些常见错误
项目GitHub地址：https://github.com/Passkou/bilibili_api
项目主页：https://passkou.com/bilibili_api
  _____                _____    _____   _  __   ____    _    _
 |  __ \      /\      / ____|  / ____| | |/ /  / __ \  | |  | |
 | |__) |    /  \    | (___   | (___   | ' /  | |  | | | |  | |
 |  ___/    / /\ \    \___ \   \___ \  |  <   | |  | | | |  | |
 | |       / ____ \   ____) |  ____) | | . \  | |__| | | |__| |
 |_|      /_/    \_\ |_____/  |_____/  |_|\_\  \____/   \____/
"""
class BilibiliApiException(Exception):
    def __init__(self, msg) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class NoPermissionException(BilibiliApiException):
    def __init__(self, msg=...) -> None:
        ...
    


class BilibiliException(BilibiliApiException):
    def __init__(self, code, msg) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class NetworkException(BilibiliApiException):
    def __init__(self, code) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class NoIdException(BilibiliApiException):
    def __init__(self) -> None:
        ...
    


class LiveException(BilibiliApiException):
    def __init__(self, msg: str) -> None:
        ...
    


class UploadException(BilibiliApiException):
    def __init__(self, msg: str) -> None:
        ...
    


